/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AdminIds": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "DiscordApplicationId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InteractionHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MainChannelId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MegacordGuildId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NasaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PhotoBucket": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StockKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}