name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_IP }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
            sudo yum update
            sudo yum install python3 -y
            sudo yum install python3-pip -y
            sudo yum install libffi-devel -y
            sudo yum install python-dev -y
            python3 -m pip install -U "discord.py[voice]" -y
            ps -ef | grep "main.py" | awk '{print $2}' | xargs sudo kill
          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT
            python3 /opt/main.py
