name: Push-to-EC2

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@main

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_IP }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_BEFORE: |
            sudo dnf upgrade -y
            sudo dnf install python3.11 python3.11-pip python3.11-devel git libffi-devel opus -y
            wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
            tar xvf ffmpeg-release-amd64-static.tar.xz
            sudo mv ffmpeg-*-amd64-static/ff* /usr/local/bin/
            sudo rm -rf ffmpeg*
            sudo timedatectl set-timezone America/New_York
          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT
            python3.11 -m pip install -r requirements.txt
            python3.11 -m pip -r requirements.txt --upgrade
            aws configure set default.region us-east-1
            aws s3 cp s3://${{ secrets.SECRET_BUCKET }}/.env .
            killall python3.11
            rm -f blackjack.lock
            python3.11 /home/ec2-user/megabot.py >/dev/null &
