name: Push-to-EC2

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@main

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_IP }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_BEFORE: |
            sudo dnf upgrade -y
            sudo dnf install python3.11 python3.11-pip python3.11-devel git libffi-devel opus java-21-amazon-corretto -y
            sudo timedatectl set-timezone America/New_York
          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT
            python3.11 -m pip install -r requirements.txt
            python3.11 -m pip uninstall discord.py -y
            python3.11 -m pip uninstall py-cord -y
            python3.11 -m pip install py-cord
            aws configure set default.region us-east-1
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws s3 cp s3://${{ secrets.SECRET_BUCKET }}/.env .
            rm local_ssh_script-before*
            killall java
            killall python3.11
            rm -f blackjack.lock
            java -jar Lavalink.jar >/dev/null &
            python3.11 /home/ec2-user/megabot.py >/dev/null &
